MD013:
  line_length: 180
  code_blocks: false
  tables: false
MD024:
  siblings_only: true
MD025:
  front_matter_title: ""
MD029:
  style: one_or_ordered
MD033:
  allowed_elements:
    - img
    - a
    - table
    - thead
    - tbody
    - tr
    - th
    - td
    - li
    - ul
    - ol
    - kbd
    - style
MD036: false
MD041: false
MD046:
  style: fenced
MD060:
  style: aligned
